name: Java CI with Allure Multi-Module Report

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
    paths: [ "**", "!*.md" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_PARALLELISM: 4

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests (all modules)
        run: mvn clean test

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Collect Allure results from all modules
        if: always()
        run: |
          mkdir -p combined-allure-results
          find . -type d -path "*/target/allure-results" -exec cp -r {}/* combined-allure-results/ \; || echo "No allure-results found"

      - name: Generate combined Allure report
        if: always()
        run: |
          mvn io.qameta.allure:allure-maven:2.12.0:report \
            -Dallure.results.directory=combined-allure-results \
            -Dallure.report.directory=combined-allure-report

      - name: Debug report contents
        if: always()
        run: |
          echo "=== Allure Results ==="
          ls -al combined-allure-results || echo "No results found"
          echo "=== Allure Report ==="
          ls -al combined-allure-report || echo "No report found"

      - name: Publish Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/combined-allure-report
          publish_branch: gh-pages
